feat: implement Docker deployment workflow and add .dockerignore

diff --git a/.github/workflows/cohort-backend-deploy.yml b/.github/workflows/cohort-backend-deploy.yml
--- a/.github/workflows/cohort-backend-deploy.yml
+++ b/.github/workflows/cohort-backend-deploy.yml
@@ -4,7 +4,6 @@ on:
   push:
     branches:
       - test
-
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -13,17 +12,39 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
+      - name: Login to Docker Hub
+        uses: docker/login-action@v4
+        with:
+          username: ${{ vars.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: QEMU
+        uses: docker/setup-qemu-action@v4
+
+      - name: set up Docker Buildx
+        uses: docker/setup-buildx-action@v4
+
+      - name: Docker Build and Push
+        run: |
+          docker build -t strangercoding/cohort-backend .
+          docker push strangercoding/cohort-backend
+
       - name: Deploy on ExCloud
         uses: appleboy/ssh-action@v1.0.3
         with:
-          host: 210.79.129.117
+          host: 210.79.128.104
           username: ubuntu
           passphrase: ${{ secrets.PASSPHRASE }}
           key: ${{ secrets.PRIVATE_KEY }}
           script: |
-            export NVM_DIR="$HOME/.nvm"
-            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-            cd /home/ubuntu/01_cohort_backend
-            git pull
-            npm install
-            pm2 restart 0
+            # Kill the existing docker container
+            sudo docker rm -f chaicode-node || true
+
+            # Again pull the fresh image from hub
+            sudo docker pull strangercoding/cohort-backend
+
+            # Run docker run -d -p 8000:8000 strangercoding/cohort-backend
+            sudo docker run -d --name cohort-backend --restart unless-stopped -p 8000:8000 strangercoding/cohort-backend
+
+            # Clean up old/unused images
+            sudo docker image prune -f
